### ISSUE TITLE
`externally-managed-python.yml` playbook fails if `upgrade.yml` playbook updates Python

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-ansible-role#205]
# 🐛 Summary #

For Debian 13 (Trixie/Testing) in [this build](https://github.com/cisagov/ansible-role-terraform/actions/runs/9843107460/job/27173601514) the `upgrade.yml` playbook upgrades the `python3` Debian package from Python 3.11 [to Python 3.12](https://packages.debian.org/trixie/python3).  This then causes the `externally-managed-python.yml` playbook to fail with:
```console
  PLAY [Ensure Python is marked as externally managed if appropriate] ************
  
  TASK [Gathering Facts] *********************************************************
  fatal: [debian13-systemd-amd64]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"failed": true, "module_stderr": "/bin/sh: 1: /usr/bin/python3.11: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
```

## To reproduce ##

Re-run the Debian 13 build linked above.

## Expected behavior ##

I expected the `externally-managed-python.yml` playbook to succeed.

## Any helpful log output or screenshots ##

See above.

**Comment by mcdonnnj** [comment]
Just some additional context on this for documentation. I believe this behavior is the result of the following sequence of events specific to Debian Testing (current Trixie):
- molecule `prepare` stage begins.
- Ansible discovers the Python interpreter  (`python3.11`).
- The `upgrade.yml` playbook is run and since Debian Testing has upgraded Python from 3.11 to 3.12 the following occurs:
  - Python 3.11 (and the `python3.11` binary) are uninstalled.
  - Python 3.12 (and the `python3.12` binary) are installed.
  - The `python3` symlink is updated.
- The `externally-managed-python.yml` playbook attempts to gather package facts.
- The previously discovered Python interpreter (`python3.11`) no longer exists so it errors since the `python3` symlink is not being used.
